---
- hosts: nas
  tasks:
  - name: install latest kernel from backports
    apt:
      pkg="linux-image-amd64"
      default_release={{ansible_distribution_release}}-backports
      state=latest

  - name: install extra packages
    apt:
      pkg="{{ item }}"
      state=present
    with_items:
      - tmux
      - zsh

  - name: install hard disk tools
    apt:
      pkg="{{ item }}"
      state=present
    with_items:
      - smartmontools
      - hddtemp
      - sysstat

  - name: ensure nestor can write on backups
    file:
      path=/srv/backups
      owner=nestor
      group=nestor
      state=directory

  roles:
    - munin
    - nginx
    - rygel
    - transmission
    - backupninja
